/************************************************************************
** dewfall - point cloud management software.
** Copyright (C) 2024  Jørgen Lind
**
** This program is free software: you can redistribute it and/or modify
** it under the terms of the GNU Affero General Public License as published by
** the Free Software Foundation, either version 3 of the License, or
** (at your option) any later version.
**
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
** GNU Affero General Public License for more details.
**
** You should have received a copy of the GNU Affero General Public License
** along with this program.  If not, see <https://www.gnu.org/licenses/>.
************************************************************************/
//
// Created by jorgen on 26.02.2024.
//

#include "input_storage_map.hpp"

#include "memory_writer.hpp"

namespace dew::core
{
// Describe a unit's blobs, whether or not the id is already known.
//
// The two cases are deliberately different in exactly one respect -- the reference count. A FRESH id
// gains its first reference. A REPLACEMENT (a LOD node regenerated by a later pass, or a unit that
// gains an attribute) re-describes the reference that already exists: it must not add one, or the
// matching dereference leaves the entry stranded at a non-zero count and its blobs are never freed.
//
// The old locations are recorded as discarded rather than dropped, so the next checkpoint can return
// the space (they leaked in the file forever before that). The freed list is only acted on once that
// checkpoint commits, so the superseded blobs stay readable until the new ones are durable.
//
// This function previously carried `assert(!_map.contains(id))` directly above the loop that exists
// only to handle a re-add -- two contradictory contracts, of which the assert won in debug builds and
// the loop won in release. Replacement is the one kept, because it is what an amend needs.
//
// Measured, so nobody has to guess later: across the whole test suite, including a 400k-point
// conversion tuned to run several LOD passes, NO conversion path reaches the replacement branch --
// tree_lod_generator skips a node that already has LOD data rather than regenerating it under the
// same id. So this is a contract being made coherent and usable, not a live bug being fixed.
void input_storage_map_t::add_storage(input_data_id_t id, attributes_id_t attributes_id, std::vector<storage_location_t> &&storage)
{
  assert(storage.size());
  auto it = _map.find(id);
  const bool replacing = it != _map.end();
  auto &value = replacing ? it->second : _map[id];
  for (auto &old_location : value.storage)
    if (old_location.size != 0)
      _discarded.emplace_back(old_location);
  value.attributes_id = attributes_id;
  value.storage = std::move(storage);
  if (!replacing)
    value.ref_count++;
}
void input_storage_map_t::append_storage(input_data_id_t id, attributes_id_t attributes_id, std::vector<storage_location_t> &&extra)
{
  // A unit GAINS an attribute: the blobs it already has stay exactly where they are, and the new one
  // is appended. Deliberately not add_storage, which replaces the whole vector and discards whatever
  // was there -- correct for a regenerated LOD node, catastrophic here, because the discarded blobs
  // would be the unit's positions and every attribute it already carried.
  //
  // The reference count is untouched for the same reason it is on a replacement: this re-describes a
  // unit that is already referenced, it does not add a reference.
  //
  // `attributes_id` must be the OLD config with the new attribute appended, so every existing slot
  // index still addresses the blob it always did. Readers resolve an attribute by name against the
  // node's own config and index this vector with the result, so a config whose order does not match
  // it mis-maps every attribute of the unit.
  assert(!extra.empty());
  auto it = _map.find(id);
  assert(it != _map.end() && "append_storage on a unit that has no storage");
  if (it == _map.end())
    return;
  auto &value = it->second;
  value.attributes_id = attributes_id;
  value.storage.reserve(value.storage.size() + extra.size());
  for (auto &location : extra)
    value.storage.push_back(location);
}

void input_storage_map_t::dereference_discard(input_data_id_t id)
{
  assert(_map.contains(id));
  auto &value = _map[id];
  value.ref_count--;
  if (value.ref_count == 0)
  {
    for (auto &location : value.storage)
      if (location.size != 0)
        _discarded.emplace_back(location);
    _map.erase(id);
  }
}

std::pair<attributes_id_t, std::vector<storage_location_t>> input_storage_map_t::dereference(input_data_id_t id)
{
  assert(_map.contains(id));
  auto &value = _map[id];
  value.ref_count--;
  if (value.ref_count == 0)
  {
    auto ret = std::make_pair(value.attributes_id, std::move(value.storage));
    _map.erase(id);
    return ret;
  }
  return std::make_pair(value.attributes_id, value.storage);
}

std::pair<attributes_id_t, std::vector<storage_location_t>> input_storage_map_t::info(input_data_id_t id) const
{
  assert(_map.contains(id));
  auto &value = _map.at(id);
  return std::make_pair(value.attributes_id, value.storage);
}

storage_location_t input_storage_map_t::location(input_data_id_t id, int attribute_index) const
{
  assert(_map.contains(id));
  auto &value = _map.at(id);
  return value.storage[attribute_index];
}
void input_storage_map_t::add_ref(input_data_id_t id)
{
  assert(_map.contains(id));
  auto &value = _map[id];
  value.ref_count++;
}
attributes_id_t input_storage_map_t::attribute_id(input_data_id_t id) const
{
  auto it = _map.find(id);
  assert(it != _map.end());
  return it->second.attributes_id;
}
uint32_t input_storage_map_t::serialized_size() const
{
  uint32_t size = 0;
  size += sizeof(uint32_t); // map size
  for (auto &[id, value] : _map)
  {
    size += sizeof(id);
    size += sizeof(value.attributes_id);
    size += sizeof(value.ref_count);
    size += sizeof(uint32_t);
    size += uint32_t(value.storage.size()) * sizeof(value.storage[0]);
  }
  return size;
}

std::pair<bool, uint8_t *> input_storage_map_t::serialize(uint8_t *buffer, const uint8_t *end) const
{
  uint8_t *ptr = buffer;

  auto map_size = uint32_t(_map.size());
  if (!write_memory(ptr, end, map_size))
    return {false, ptr};

  for (auto &[id, value] : _map)
  {
    if (!write_memory(ptr, end, id))
      return {false, ptr};
    if (!write_memory(ptr, end, value.attributes_id))
      return {false, ptr};
    if (!write_memory(ptr, end, value.ref_count))
      return {false, ptr};
    auto storage_size = uint32_t(value.storage.size());
    if (!write_memory(ptr, end, storage_size))
      return {false, ptr};
    if (!write_vec_type(ptr, end, value.storage))
      return {false, ptr};
  }
  return {true, ptr};
}

std::pair<bool, const uint8_t *> input_storage_map_t::deserialize(const uint8_t *buffer, const uint8_t *end)
{
  auto ptr = buffer;
  uint32_t map_size;
  if (!read_memory(ptr, end, map_size))
    return {false, ptr};
  for (uint32_t i = 0; i < map_size; i++)
  {
    input_data_id_t id;
    attributes_id_t attributes_id;
    uint32_t ref_count;
    uint32_t storage_size;
    std::vector<storage_location_t> storage;
    if (!read_memory(ptr, end, id))
      return {false, ptr};
    if (!read_memory(ptr, end, attributes_id))
      return {false, ptr};
    if (!read_memory(ptr, end, ref_count))
      return {false, ptr};
    if (!read_memory(ptr, end, storage_size))
      return {false, ptr};
    if (!read_vec_type(ptr, end, storage, storage_size))
      return {false, ptr};
    _map[id] = {attributes_id, std::move(storage), ref_count};
  }
  return {true, ptr};
}

} // namespace dew::core
